In [1]:
import numpy as np

In [2]:
# Generate an np array of (a) vector of lenght 50
ma = np.arange(50)
ma

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [3]:
# (b) two dimension of shape 5x4. Both uniformly distributed between 0 and 1
mb = np.random.random((5,4))
print('The Two Dimension Array of 5x4 Uniformly Distributed btw 0 & 1 are :\n',mb)

The Two Dimension Array of 5x4 Uniformly Distributed btw 0 & 1 are :
 [[0.71362363 0.57864177 0.62272892 0.58171783]
 [0.04873588 0.19534599 0.79619344 0.48209466]
 [0.4257564  0.60433233 0.22508787 0.66629841]
 [0.03929161 0.67777723 0.1756855  0.60731778]
 [0.24478428 0.68569193 0.9060966  0.67378939]]


In [4]:
# 2. Split the two dimension array in 1 above into three arrays taking the first two rows, 
# follow by the next two rows and put the remaining row in another variable

i_array, ii_array, iii_array = np.vsplit(mb,[2,4])
print("The 1st array is:\n", i_array,"\n") 

print("The 2nd array is:\n", ii_array,"\n")

print("The 3rd array is:\n", iii_array,"\n")


The 1st array is:
 [[0.71362363 0.57864177 0.62272892 0.58171783]
 [0.04873588 0.19534599 0.79619344 0.48209466]] 

The 2nd array is:
 [[0.4257564  0.60433233 0.22508787 0.66629841]
 [0.03929161 0.67777723 0.1756855  0.60731778]] 

The 3rd array is:
 [[0.24478428 0.68569193 0.9060966  0.67378939]] 



In [5]:
# 3. Split the vector  in 1a above into three arrays by taking the first 15, 
# follow by the next 20 and the remaining into another variable.
array1, array2, array3 = np.split(mb,(15,35))

print("The 1st 15 arrays are:\n", array1,"\n") 

print("The next 20 arrays are:\n", array2,"\n")

print("The Remaining arrays are:\n", array3,"\n")

The 1st 15 arrays are:
 [[0.71362363 0.57864177 0.62272892 0.58171783]
 [0.04873588 0.19534599 0.79619344 0.48209466]
 [0.4257564  0.60433233 0.22508787 0.66629841]
 [0.03929161 0.67777723 0.1756855  0.60731778]
 [0.24478428 0.68569193 0.9060966  0.67378939]] 

The next 20 arrays are:
 [] 

The Remaining arrays are:
 [] 



In [10]:
# 4a. Create a 4x5 array: (a). Using manual method (b). Using randomly generated value between 0 and 1 (c). Using array of ones

np.array([[1,1,1,1,1],[3,3,3,3,3],[2,2,2,2,2],[4,4,4,4,4]])

array([[1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3],
       [2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4]])

In [12]:
#4b. Create a 4x5 array: (b). Using randomly generated value between 0 and 1 
np.random.random((4,5))

array([[0.0681016 , 0.86025547, 0.88059701, 0.06478923, 0.72087461],
       [0.36832643, 0.55538279, 0.73530934, 0.70843285, 0.3528773 ],
       [0.29651905, 0.46341451, 0.46585703, 0.30213557, 0.40488468],
       [0.11074743, 0.7995893 , 0.84624304, 0.18472899, 0.87046955]])

In [6]:
# 4. Create a 4x5 array:(c). Using array of ones
np.ones([4,5], dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])